- name: Deploy over SSH
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: deploy
    key: ${{ secrets.SERVER_SSH_KEY }}
    source: "bin/tamagoshit"
    target: "/opt/tamagoshit_api/bin"

- name: Set DB_PASSWORD and restart service
  uses: appleboy/ssh-action@v0.1.10
  env:
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: deploy
    key: ${{ secrets.SERVER_SSH_KEY }}
    envs: DB_PASSWORD
    script: |
      echo "DB_PASSWORD=$DB_PASSWORD" | sudo tee /etc/tamagoshit/env > /dev/null
      sudo chmod 600 /etc/tamagoshit/env
      sudo systemctl restart tamagoshit